# general
project: cornell-birdcall-identification
log_level: INFO
debug: 1

# global
seed: 42
device: cuda
sr: 32000
duration: 5 # chunks of 5 secs
img_size: 224 # height (width becomes 542) 
verbose: 1
n_classes: 264
threshold: 0.5 # 0.65
model: "ConvNet" # ConvNet SimpleConvNet
preprocess: False # set to True if resampling is required
with_cv: False # whether to use kfold CV

# filepaths
paths:
  root: kaggle/cornell-birdcall-identification
  train: data/train_combined.csv
  test: data/test.csv
  audio: data/resampled_audio
  ebird_code: data/ebird_codes.json
  best_pth: checkpoints/00_convnet/best_pth/checkpoint.pt # 00_vggish
  snap_pth: checkpoints/00_convnet/snap_pth/
  logs: logs
  splits: data/splits.json

# melspec parameters
mel_params:
  n_mels: 128
  fmin: 30 # lowest hearable freq?
  fmax: 16000 # sr // 2 i.e nyquist frequency?
  n_fft: 2048 # default value 
  hop_length: 512 # default value

# training hyperparams
hyperparams:
  cv: 
    name: StratifiedKFold
    splits: 3
  epochs: 30 # 100
  batch_size: 32
  valid_size: 0.2
  num_workers: 4
  scheduler: CosineAnnealingLR
  lr: 0.001
  t_max: 10